### ISSUE TITLE
Interface création salle privée V1

### ISSUE THREAD

**Issue by BastLast** [Canard-Ecarlate/Frontend#10]
FAIRE l'écran de création de salle
LA TACHE TERMINEE LORSQUE sur l'écran je peux sélectionner le nombre de joueur, renseigner nom de la salle
Tâche création : #60

![CreerSalon](https://user-images.githubusercontent.com/45668758/151990934-eddb7cc5-6e45-42e7-a993-d8c6e988ca9b.png)

**Comment by GHSebamo** [comment]
!![image](https://user-images.githubusercontent.com/28093716/154723986-cce21741-9d4c-4e05-83ca-846eb5df772a.png)
![image](https://user-images.githubusercontent.com/28093716/154724045-46e62998-a697-4ca6-867c-8db0d73fea23.png)
