### ISSUE TITLE
Interface rejoindre une salle privée V1

### ISSUE THREAD

**Issue by BastLast** [Canard-Ecarlate/Frontend#15]
FAIRE l'interface de saisi de code pour rejoindre une salle privée
LA TACHE EST TERMINEE LORSQUE je peux :

 - [x] Naviguer vers la page "Créer salon"
 - [x] Saisir un code et cliquer sur le bouton me permettant de rejoindre une salle privée
 - [x] Retourner vers l'accueil

![RejoindreSalonPrive](https://user-images.githubusercontent.com/45668758/151986382-f0510b0d-74fe-43c1-90bc-3f142b0a91aa.png)

**Comment by BastLast** [comment]
In GitLab by @Theo_S on Sep 21, 2021, 10:23

assigned to @Theo_S

**Comment by GHSebamo** [comment]
[image](https://user-images.githubusercontent.com/28093716/154675438-891267f6-2d2b-4473-8d7e-47c30eb137d0.png)
![image](https://user-images.githubusercontent.com/28093716/154676148-c7163f10-537b-47b0-9fb1-ea0825971fac.png)
