### ISSUE TITLE
Interface jouer

### ISSUE THREAD

**Issue by BastLast** [Canard-Ecarlate/Frontend#17]
FAIRE l'écran de la liste des salles
LA TACHE EST TERMINEE LORSQUE Sur l'écran je peux (il faut seulement prévoir les emplacements et boutons) :

- [x] Voir les infos (à déterminer) de la partie en direct
- [x] Piocher chez un autre joueur uniquement lorsque c'est mon tour (tâche #44)
- [x] Voir/cacher son rôle et ses cartes
- [x] Naviguer vers les paramètres (écran non implémenter)
- [x] Avoir accès au chat (écran non implémenter)

![Jeu](https://user-images.githubusercontent.com/45668758/151985785-36c33afd-8238-432d-ab62-c7cb765d559b.png)

**Comment by BastLast** [comment]
In GitLab by @Theo_S on Sep 21, 2021, 10:21

assigned to @Theo_S

**Comment by GHSebamo** [comment]
![image](https://user-images.githubusercontent.com/28093716/152822724-7d74bd1d-c222-4309-8d0e-a8aecaf763de.png)
![image](https://user-images.githubusercontent.com/28093716/152825029-93626ec2-c442-4e9a-9302-47833ac83525.png)
![image](https://user-images.githubusercontent.com/28093716/152825086-7f4dc19e-1647-4782-99ef-74ae8c0a77f1.png)
![image](https://user-images.githubusercontent.com/28093716/152825311-44fa1eda-0d75-4fba-9a8e-0ca924edd597.png)
