### ISSUE TITLE
Interface démarrage

### ISSUE THREAD

**Issue by BastLast** [Canard-Ecarlate/Frontend#18]
FAIRE les interfaces de démarrage
LA TACHE EST TERMINEE LORSQUE les interfaces connexion, inscription et le splash screen sont terminées. 
Depuis l'écran de connexion, je peux : 

- [x] Me connecter (tâche #55)
- [x] Bouton de navigation vers mot de passe oublié (écran non implémenté)

Depuis l'écran d'inscription, je peux : 

- [x] M'inscrire (l'inscription connecte automatiquement) (tâche #56)
- [x] Voir les CGU (lien vers le site web)

![Connexion](https://user-images.githubusercontent.com/45668758/151985531-73e25cab-1b7f-47e5-a554-7c2678cc9f62.png)

**Comment by senetal** [comment]
Splash screen + login/signup
