### ISSUE TITLE
Interface salle d'attente

### ISSUE THREAD

**Issue by BastLast** [Canard-Ecarlate/Frontend#4]
FAIRE l'écran de salle d'attente
LA TACHE EST TERMINEE LORSQUE sur l'écran je peux  : 
- [ ] Voir les autres joueurs présents dans la partie et leurs infos (tâche #58)
- [ ] Voir les infos de la salle (nom, code pour l'instant)
- [x] Indiquer que je suis prêt
- [x] Naviguer vers les paramètres de l'application (interface non implémenté)
- [ ] Naviguer vers mes customisations (interface non implémenté)
- [ ] Naviguer vers les règles du jeu (interface non implémenté)
- [ ] Naviguer vers la liste des cartes (interface non implémenté)

Propriétaire only : 
- [ ] Naviguer vers la configuration de la partie (interface non implémenté)
- [ ] Exclure un joueur (fonctionnalité non implémenter)
- [ ] Donner la propriété à un autre joueur (fonctionnalité non implémenter)

⚠️ Toutes les navigations se font à partir d'un sous-menu accessible depuis un même item (barman)

![layout_bar_v2](https://user-images.githubusercontent.com/45668758/152862254-a1fab8d1-947a-4514-b18a-008c9e63f7ab.png)

**Comment by GHSebamo** [comment]
![image](https://user-images.githubusercontent.com/28093716/155680908-62940166-79c0-48ae-8e19-af9870e02b23.png)

**Comment by GHSebamo** [comment]
Il manque des trucs
Mais pas le temps...
