### ISSUE TITLE
Implémenter la méthode signalR PlayerReady(RoomId)

### ISSUE THREAD

**Issue by Evi-Raoul** [Canard-Ecarlate/Frontend#42]
FAIRE une méthode qui indique qu'un joueur est prêt à jouer
LA TACHE EST TERMINEE LORSQUE je peux voir quels joueurs sont prêts à jouer en fonction des informations envoyé par le back

**Comment by Vincent-Letourmy** [comment]
On peut push les messages "i'm ready" depuis l'appel REST ReadyToGo() à tous les membres du groupe signalR de la salle, il reste à envoyé les bonnes infos (la liste des joueurs prêts actualisée).

**Comment by Vincent-Letourmy** [comment]
J'ai refait la méthode pour qu'elle ne soit que dans le hub, plus dans le contrôleur. Fonctionne

**Comment by Vincent-Letourmy** [comment]
La méthode renvoie le playerInRoom, qui a un booléen ready mis à jour :)
