### ISSUE TITLE
Implémenter la méthode signalR UpdatePlayerListOf(RoomId)

### ISSUE THREAD

**Issue by Evi-Raoul** [Canard-Ecarlate/Frontend#49]
FAIRE une méthode qui met à jour la liste des joueurs dans le salon
LA TACHE EST TERMINEE LORSQUE, quand le serveur notifie l'arrivée d'un joueur ou le départ d'un joueur, la liste des joueurs dans la salle se met à jour. Le départ enlève le joueur et l'arrivée l'ajoute.

**Comment by Vincent-Letourmy** [comment]
Quand l'appel rest JoinRoom renvoye "OK code 200", le front se connecte à signalR au bon groupe et signal sa présence. Il faut maintenant envoyer les bonnes infos (la liste des joueurs actualisée) et envoyer la bonne url de gameApi où se connecter.
