### ISSUE TITLE
Inscription à l'application

### ISSUE THREAD

**Issue by Evi-Raoul** [Canard-Ecarlate/Frontend#56]
FAIRE l'inscription d'un utilisateur à l'application
LA TACHE EST TERMINEE LORSQUE l'utilisateur a pu renseigner son pseudo, son mail, son mot de passe et signer les conditions générales. Une fois l'inscription réussie, l'utilisateur est redirigé vers la vue accueil.
L'inscription est bloquée si :
- [x] le mot de passe ne satisfait pas les recommandations 
- [x] le mail est déjà utilisé
- [x] le pseudo est déjà utilisé
- [x] les conditions générales ne sont pas acceptées
- [x] l'accès au réseau est impossible

**Comment by senetal** [comment]
Note : le front bloque le bouton pour s'inscrire si le mot de passe est vide ou si les conditions ne sont pas acceptées. Solution temporaire, il faudra rendre ça plus intuitif.
