### ISSUE TITLE
Interface accueil

### ISSUE THREAD

**Issue by BastLast** [Canard-Ecarlate/Frontend#9]
FAIRE la vue accueil
LA TACHE EST TERMINEE LORSQUE depuis cette écran je peux : 

- [x] Naviguer vers la liste des salles (interface non implémentée)
- [x] Naviguer vers le menu de customisation (interface non implémentée)
- [x] Naviguer vers les annonces/actualités (interface non implémentée)
- [x] Naviguer vers le shop (interface non implémentée)
- [x] Naviguer vers les règles du jeu (interface non implémentée)
- [x] Naviguer vers la liste des cartes (interface non implémentée)
- [x] Naviguer vers les paramètres (interface non implémentée)
- [x] Naviguer vers le profil (interface non implémentée)

![Accueil](https://user-images.githubusercontent.com/45668758/151989214-e9d1ddc2-556b-4281-b900-b40ba3eb2059.png)

**Comment by senetal** [comment]
Page de démarrage (splash screen) + login/signup
